version: "3.7"
volumes:
    minio_data:
        external: true
services:
    prometheus:
        image: prom/prometheus
        command: --config.file=/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
    minio:
        image: minio/minio
        environment:
            - MINIO_ROOT_USER=ROOTUSER
            - MINIO_ROOT_PASSWORD=CHANGEME123
            - MINIO_PROMETHEUS_AUTH_TYPE=public
            - MINIO_CACHE="on"
            - MINIO_CACHE_DRIVES=/mnt/drive1,/mnt/drive2
            - MINIO_CACHE_QUOTA=80 # 80% of the drive will be used for caching
            - MINIO_CACHE_AFTER=1 # Object will be cached after the first request to it
            - MINIO_CACHE_WATERMARK_LOW=70 # Least accessed objects will be erased after the cache disk reaches the 70% watermark
            - MINIO_CACHE_WATERMARK_HIGH=90
            - MINIO_PROMETHEUS_URL=http://prometheus:9090
            - MINIO_PROMETHEUS_JOB_ID=minio-job
        command: server /data --console-address ":9001"
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes: 
            - minio_data:/data