global:
    scrape_interval: 2s
    scrape_timeout: 2s
    evaluation_interval: 2s

scrape_configs:
  - job_name: minio-job
    honor_timestamps: true
    scrape_interval: 2s
    scrape_timeout: 2s
    metrics_path: /minio/prometheus/metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
    - targets:
      - minio:9000
